import React from "react";
import { Box, Container, Flex } from "@chakra-ui/react";
import Delete from "./Delete";
import Key from "./Key";

export default function Keyboard({
  setGuesses,
  guesses,
  check_answer,
  answer,
  attempts,
  updateGuess_Array,
}) {
  return (
    <Container fontSize="lg">
      <Flex justifyContent="center" gridGap="3" height={12}>
        <Key
          character={"Q"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"W"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"E"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"R"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"T"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"Y"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"U"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"I"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"O"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"P"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
      </Flex>
      <Flex justifyContent="center" gridGap="3" height={12}>
        <Key
          character={"A"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"S"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"D"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"F"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"G"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"H"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"J"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"K"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"L"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
      </Flex>
      <Flex justifyContent="center" gridGap="3">
        <Box>
          <Key
            character={"ENTER"}
            setGuesses={setGuesses}
            guesses={guesses}
            answer={answer}
            check_answer={check_answer}
            attempts={attempts}
            updateGuess_Array={updateGuess_Array}
          />
        </Box>
        <Key
          character={"Z"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"X"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"C"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"V"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"B"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"N"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Key
          character={"M"}
          setGuesses={setGuesses}
          guesses={guesses}
          attempts={attempts}
          updateGuess_Array={updateGuess_Array}
        />
        <Box>
          <Delete
            character={"DELETE"}
            setGuesses={setGuesses}
            guesses={guesses}
            attempts={attempts}
          />
        </Box>
      </Flex>
    </Container>
  );
}
